name: Download


on:
    [push]

jobs:
   build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
                presist-credentials: false
                fetch-depth: 0
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
              python-version: '3.8'
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r ./requirements.txt

          - name: Run script to download 
            run: |
              python ./download_image.py
          - name: commit
            run: |
                  git config --global user.email 44770157@qq.com
                  git config --global user.name bgcode
                  git add .
                  git commit -m "update" 
          - name: Push to another repository
            env:
            ACCESS_TOKEN: ${{ secrets.AAA_TOKEN }}
            run: |
                git remote add target https://github.com/bgvioletsky/testaction.git
                git push target HEAD:refs/heads/main
          
          