name: Create and push file
on: [push]
jobs:
  create_and_push_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create file
      run: |
        touch newfile.txt
        echo "Hello, world!" > newfile.txt
    - name: Commit files
      run: |
        git config --global user.email 44770157@qq.com
        git config --global user.name bgcode
        git add .
        git commit -m "update" 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token:  ${{ secrets.SSS }}
        branch: main