name: 'GitHub Actions Weather Bot'


on:
  [push]
#   schedule:
#     - cron: '0 21 * * *'

jobs:
    GetWeather:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r ./requirements.txt

        - name: Run script to download 
          run: |
               python ./getweather.py
        - name: Send email
          uses: dawidd6/action-send-mail@v3.10.0           
          with:
            serveraddress: smtp.163.com
            serverport: 465
            username: bglhcode@163.com
            password: XUYPGYSEDDCABUMA
            subject: Shanghai Weather Report
            body: completed successfully!
            html_body: file://text.html
            to: 447701537@qq.com
            from: GitHub Actions
            content_type: text/html

