name: Push File to Repository

on:
  [push]

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Hello, World!" > example.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: example-artifact
          path: example.txt
